name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: todo
          MYSQL_USER: todo
          MYSQL_PASSWORD: todo

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - uses: actions/checkout@v3
      - run: |
          go install github.com/k0kubun/sqldef/cmd/mysqldef@v0.13.7
          mysqldef -u todo -p todo -h 127.0.0.1 -P 3306 todo < ./go_todo_app/_tools/mysql/schema.sql
      - run: |
          cd go_todo_app
          go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
