name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - uses: actions/checkout@v3
      - run: |
          cd go_todo_app
          go test ./... -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v0
